id: P0AE4FD8D
initial_creation_type: ocr
source_metadata:
  volumes:
    5c89421ee9854dbc8d06fa6e755a9f78:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བཀྲ་ཤིས་ཀྱི་ཚིགས་སུ་བཅད་པ།
      total_pages: 1880
      volume_number: 116
