id: D84EA848B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-07T09:23:01+00:00'
last_modified: '2022-05-30T06:39:10.945411+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '9161':
      image_group_id: I1PD95961
      title: བཀྲ་ཤིས་ཀྱི་ཚིགས་སུ་བཅད་པ།
      total_pages: 1880
      order: 116
      base_file: 9161.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
